"""Initial database migration

Revision ID: 102c15d18499
Revises: 
Create Date: 2023-12-03 13:05:48.854345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '102c15d18499'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nota_pedidos', schema=None) as batch_op:
        batch_op.drop_constraint('nota_pedidos_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'mesas', ['mesa_id'], ['id'], ondelete='SET DEFAULT')

    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.drop_constraint('FK_imagen_producto', type_='foreignkey')
        batch_op.drop_constraint('FK_tipo_producto', type_='foreignkey')
        batch_op.create_foreign_key('FK_tipo_producto', 'tipos', ['tipo_id'], ['id'], ondelete='SET DEFAULT')
        batch_op.create_foreign_key('FK_imagen_producto', 'imagenes', ['imagen_id'], ['id'], ondelete='SET DEFAULT')

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_constraint('fk_Role', type_='foreignkey')
        batch_op.drop_constraint('FK_imagen_usuario', type_='foreignkey')
        batch_op.create_foreign_key('FK_imagen_usuario', 'imagenes', ['imagen_id'], ['id'], ondelete='SET DEFAULT')
        batch_op.create_foreign_key('fk_Role', 'roles', ['role_id'], ['id'], ondelete='SET DEFAULT')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_constraint('fk_Role', type_='foreignkey')
        batch_op.drop_constraint('FK_imagen_usuario', type_='foreignkey')
        batch_op.create_foreign_key('FK_imagen_usuario', 'imagenes', ['imagen_id'], ['id'])
        batch_op.create_foreign_key('fk_Role', 'roles', ['role_id'], ['id'])

    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.drop_constraint('FK_imagen_producto', type_='foreignkey')
        batch_op.drop_constraint('FK_tipo_producto', type_='foreignkey')
        batch_op.create_foreign_key('FK_tipo_producto', 'tipos', ['tipo_id'], ['id'])
        batch_op.create_foreign_key('FK_imagen_producto', 'imagenes', ['imagen_id'], ['id'])

    with op.batch_alter_table('nota_pedidos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('nota_pedidos_ibfk_2', 'mesas', ['mesa_id'], ['id'])

    # ### end Alembic commands ###
