"""Agregado nombre_usuario Tabla Usuario

Revision ID: 468d41503bde
Revises: 7c71ed617081
Create Date: 2024-01-18 13:58:49.714448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '468d41503bde'
down_revision = '7c71ed617081'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre_usuario', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_usuarios_nombre_usuario'), ['nombre_usuario'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_nombre_usuario'))
        batch_op.drop_column('nombre_usuario')


    # ### end Alembic commands ###
