"""feature detalle venta nueva columna y nota de pedido columnas pagos

Revision ID: 588af4bf5548
Revises: 9fc61b5ce487
Create Date: 2023-11-30 20:47:51.498231

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '588af4bf5548'
down_revision = '9fc61b5ce487'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #with op.batch_alter_table('detalle_venta', schema=None) as batch_op:
    #    batch_op.add_column(sa.Column('dv_atendido', sa.Boolean(), nullable=True))

    with op.batch_alter_table('nota_pedidos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pago_efectivo', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('pago_yape', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('pago_visa', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('comentario', sa.String(length=128), nullable=False))
        batch_op.drop_constraint('nota_pedidos_ibfk_4', type_='foreignkey')
        batch_op.create_foreign_key(None, 'mesas', ['mesa_id'], ['id'], ondelete='SET DEFAULT')
        batch_op.drop_column('tipo_pago')

    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.drop_constraint('FK_tipo_producto', type_='foreignkey')
        batch_op.drop_constraint('FK_imagen_producto', type_='foreignkey')
        batch_op.create_foreign_key('FK_tipo_producto', 'tipos', ['tipo_id'], ['id'], ondelete='SET DEFAULT')
        batch_op.create_foreign_key('FK_imagen_producto', 'imagenes', ['imagen_id'], ['id'], ondelete='SET DEFAULT')

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_constraint('FK_imagen_usuario', type_='foreignkey')
        batch_op.drop_constraint('fk_Role', type_='foreignkey')
        batch_op.create_foreign_key('fk_Role', 'roles', ['role_id'], ['id'], ondelete='SET DEFAULT')
        batch_op.create_foreign_key('FK_imagen_usuario', 'imagenes', ['imagen_id'], ['id'], ondelete='SET DEFAULT')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_constraint('FK_imagen_usuario', type_='foreignkey')
        batch_op.drop_constraint('fk_Role', type_='foreignkey')
        batch_op.create_foreign_key('fk_Role', 'roles', ['role_id'], ['id'])
        batch_op.create_foreign_key('FK_imagen_usuario', 'imagenes', ['imagen_id'], ['id'])

    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.drop_constraint('FK_imagen_producto', type_='foreignkey')
        batch_op.drop_constraint('FK_tipo_producto', type_='foreignkey')
        batch_op.create_foreign_key('FK_imagen_producto', 'imagenes', ['imagen_id'], ['id'])
        batch_op.create_foreign_key('FK_tipo_producto', 'tipos', ['tipo_id'], ['id'])

    with op.batch_alter_table('nota_pedidos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_pago', mysql.VARCHAR(length=64), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('nota_pedidos_ibfk_4', 'mesas', ['mesa_id'], ['id'])
        batch_op.drop_column('comentario')
        batch_op.drop_column('pago_visa')
        batch_op.drop_column('pago_yape')
        batch_op.drop_column('pago_efectivo')

    with op.batch_alter_table('detalle_venta', schema=None) as batch_op:
        batch_op.drop_column('dv_atendido')

    # ### end Alembic commands ###
