"""refactor piso y numero de mesa poniendo restriccion Unique

Revision ID: 7c71ed617081
Revises: 1775d240f2b4
Create Date: 2024-01-07 19:23:56.869429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c71ed617081'
down_revision = '1775d240f2b4'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("ALTER TABLE nota_pedidos DROP FOREIGN KEY nota_pedidos_ibfk_2")
    
    # Remove auto_increment from id column
    op.execute('ALTER TABLE mesas MODIFY id INT NOT NULL')
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mesas', schema=None) as batch_op:
        batch_op.drop_constraint('PK_mesa', type_='primary')
        batch_op.create_primary_key('PK_mesa', ['id'])

    op.execute("ALTER TABLE mesas MODIFY id INT NOT NULL AUTO_INCREMENT")

    # Add foreign key constraint back to nota_pedidos table
    op.execute("ALTER TABLE nota_pedidos ADD CONSTRAINT nota_pedidos_ibfk_2 FOREIGN KEY (mesa_id) REFERENCES mesas(id)")

    # Add unique constraint to piso and numero_mesa
    op.create_unique_constraint('_piso_numero_mesa_uc', 'mesas', ['piso', 'numero_mesa'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Drop unique constraint from piso and numero_mesa
    op.drop_constraint('_piso_numero_mesa_uc', 'mesas', type_='unique')
    
    # Drop foreign key constraint in nota_pedidos table
    op.execute("ALTER TABLE nota_pedidos DROP FOREIGN KEY nota_pedidos_ibfk_2")

    # Remove auto_increment from id column
    op.execute('ALTER TABLE mesas MODIFY id INT NOT NULL')
    with op.batch_alter_table('mesas',schema=None) as batch_op:
        batch_op.drop_constraint('PK_mesa', type_='primary')
        batch_op.create_primary_key('PK_mesa', ['id','piso','numero_mesa'])
    # Add auto_increment back to id column
    op.execute("ALTER TABLE mesas MODIFY id INT NOT NULL AUTO_INCREMENT")

    # Add foreign key constraint back to nota_pedidos table
    op.execute("ALTER TABLE nota_pedidos ADD CONSTRAINT nota_pedidos_ibfk_2 FOREIGN KEY (mesa_id) REFERENCES mesas(id)")
    # ### end Alembic commands ###

    # ### end Alembic commands ###
