"""Agregando Tabla Nota_Pedido,detalle_venta y Cliente

Revision ID: 8072196fcea5
Revises: 068e87c483f4
Create Date: 2023-11-15 18:45:32.496678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8072196fcea5'
down_revision = '068e87c483f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.drop_constraint('FK_imagen_producto', type_='foreignkey')
        batch_op.drop_constraint('FK_tipo_producto', type_='foreignkey')
        batch_op.create_foreign_key('FK_imagen_producto', 'imagenes', ['imagen_id'], ['id'], ondelete='SET DEFAULT')
        batch_op.create_foreign_key('FK_tipo_producto', 'tipos', ['tipo_id'], ['id'], ondelete='SET DEFAULT')

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_constraint('FK_imagen_usuario', type_='foreignkey')
        batch_op.drop_constraint('fk_Role', type_='foreignkey')
        batch_op.create_foreign_key('FK_imagen_usuario', 'imagenes', ['imagen_id'], ['id'], ondelete='SET DEFAULT')
        batch_op.create_foreign_key('fk_Role', 'roles', ['role_id'], ['id'], ondelete='SET DEFAULT')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_constraint('fk_Role', type_='foreignkey')
        batch_op.drop_constraint('FK_imagen_usuario', type_='foreignkey')
        batch_op.create_foreign_key('fk_Role', 'roles', ['role_id'], ['id'])
        batch_op.create_foreign_key('FK_imagen_usuario', 'imagenes', ['imagen_id'], ['id'])

    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.drop_constraint('FK_tipo_producto', type_='foreignkey')
        batch_op.drop_constraint('FK_imagen_producto', type_='foreignkey')
        batch_op.create_foreign_key('FK_tipo_producto', 'tipos', ['tipo_id'], ['id'])
        batch_op.create_foreign_key('FK_imagen_producto', 'imagenes', ['imagen_id'], ['id'])

    # ### end Alembic commands ###
