"""refactor eliminando relation ship usuario mesa

Revision ID: 9fc61b5ce487
Revises: 561b8bcaf1a5
Create Date: 2023-11-25 21:48:09.054114

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9fc61b5ce487'
down_revision = '561b8bcaf1a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #with op.batch_alter_table('mesas', schema=None) as batch_op:
        #batch_op.drop_constraint('mesas_ibfk_1', type_='foreignkey')
    #    batch_op.drop_column('usuario_id')

    #with op.batch_alter_table('nota_pedidos', schema=None) as batch_op:
    #    batch_op.drop_constraint('nota_pedidos_ibfk_2', type_='foreignkey')
    #    batch_op.create_foreign_key(None, 'mesas', ['mesa_id'], ['id'], ondelete='SET DEFAULT')

    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.drop_constraint('FK_tipo_producto', type_='foreignkey')
        batch_op.drop_constraint('FK_imagen_producto', type_='foreignkey')
        batch_op.create_foreign_key('FK_tipo_producto', 'tipos', ['tipo_id'], ['id'], ondelete='SET DEFAULT')
        batch_op.create_foreign_key('FK_imagen_producto', 'imagenes', ['imagen_id'], ['id'], ondelete='SET DEFAULT')

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_constraint('FK_imagen_usuario', type_='foreignkey')
        batch_op.drop_constraint('fk_Role', type_='foreignkey')
        batch_op.create_foreign_key('fk_Role', 'roles', ['role_id'], ['id'], ondelete='SET DEFAULT')
        batch_op.create_foreign_key('FK_imagen_usuario', 'imagenes', ['imagen_id'], ['id'], ondelete='SET DEFAULT')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_constraint('FK_imagen_usuario', type_='foreignkey')
        batch_op.drop_constraint('fk_Role', type_='foreignkey')
        batch_op.create_foreign_key('fk_Role', 'roles', ['role_id'], ['id'])
        batch_op.create_foreign_key('FK_imagen_usuario', 'imagenes', ['imagen_id'], ['id'])

    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.drop_constraint('FK_imagen_producto', type_='foreignkey')
        batch_op.drop_constraint('FK_tipo_producto', type_='foreignkey')
        batch_op.create_foreign_key('FK_imagen_producto', 'imagenes', ['imagen_id'], ['id'])
        batch_op.create_foreign_key('FK_tipo_producto', 'tipos', ['tipo_id'], ['id'])

    with op.batch_alter_table('nota_pedidos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('nota_pedidos_ibfk_2', 'mesas', ['mesa_id'], ['id'])

    with op.batch_alter_table('mesas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usuario_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('mesas_ibfk_1', 'usuarios', ['usuario_id'], ['id'])

    # ### end Alembic commands ###
