"""feature Tabla Mesa

Revision ID: da718957c562
Revises: 9a4689a4232c
Create Date: 2023-11-25 21:07:03.308649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da718957c562'
down_revision = '9a4689a4232c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nota_pedidos', schema=None) as batch_op:
        #batch_op.add_column(sa.Column('estado_pago', sa.Boolean(), nullable=True))
        #batch_op.add_column(sa.Column('estado_atendido', sa.Boolean(), nullable=True))
        #batch_op.add_column(sa.Column('mesa_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'mesas', ['mesa_id'], ['id'])

    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.drop_constraint('FK_tipo_producto', type_='foreignkey')
        batch_op.drop_constraint('FK_imagen_producto', type_='foreignkey')
        batch_op.create_foreign_key('FK_tipo_producto', 'tipos', ['tipo_id'], ['id'], ondelete='SET DEFAULT')
        batch_op.create_foreign_key('FK_imagen_producto', 'imagenes', ['imagen_id'], ['id'], ondelete='SET DEFAULT')

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_constraint('fk_Role', type_='foreignkey')
        batch_op.drop_constraint('FK_imagen_usuario', type_='foreignkey')
        batch_op.create_foreign_key('FK_imagen_usuario', 'imagenes', ['imagen_id'], ['id'], ondelete='SET DEFAULT')
        batch_op.create_foreign_key('fk_Role', 'roles', ['role_id'], ['id'], ondelete='SET DEFAULT')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_constraint('fk_Role', type_='foreignkey')
        batch_op.drop_constraint('FK_imagen_usuario', type_='foreignkey')
        batch_op.create_foreign_key('FK_imagen_usuario', 'imagenes', ['imagen_id'], ['id'])
        batch_op.create_foreign_key('fk_Role', 'roles', ['role_id'], ['id'])

    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.drop_constraint('FK_imagen_producto', type_='foreignkey')
        batch_op.drop_constraint('FK_tipo_producto', type_='foreignkey')
        batch_op.create_foreign_key('FK_imagen_producto', 'imagenes', ['imagen_id'], ['id'])
        batch_op.create_foreign_key('FK_tipo_producto', 'tipos', ['tipo_id'], ['id'])

    with op.batch_alter_table('nota_pedidos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('mesa_id')
        batch_op.drop_column('estado_atendido')
        batch_op.drop_column('estado_pago')

    # ### end Alembic commands ###
