"""Agregando columna anulado a nota de pedido

Revision ID: ead09835e8c6
Revises: f07832e38e3c
Create Date: 2024-01-22 18:37:41.005653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ead09835e8c6'
down_revision = 'f07832e38e3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nota_pedidos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('anulado', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nota_pedidos', schema=None) as batch_op:

        batch_op.drop_column('anulado')

    # ### end Alembic commands ###
