"""Agregando Nota columna vuelto

Revision ID: f07832e38e3c
Revises: 468d41503bde
Create Date: 2024-01-18 21:23:31.058782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f07832e38e3c'
down_revision = '468d41503bde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
   
    with op.batch_alter_table('nota_pedidos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vuelto', sa.Numeric(precision=10, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nota_pedidos', schema=None) as batch_op:
        batch_op.drop_column('vuelto')


    # ### end Alembic commands ###
